[package]
name = "stm32f4_hal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "^1.0"

[dependencies]
num-traits = "^0.2.14"

[features]
default = ["default_panic"]
default_panic = []
